`include "uvm_macros.svh"
//import uvm_pkg::*;

`uvm_analysis_imp_decl(_item)
`uvm_analysis_imp_decl(_currency)
`uvm_analysis_imp_decl(_dispense)
`uvm_analysis_imp_decl(_cfg)

class vending_sb extends uvm_scoreboard;
  `uvm_component_utils(vending_sb)

  // analysis imports using suffixed classes generated by macros
  uvm_analysis_imp_item     #(item_select_transaction, vending_sb) item_export;
  uvm_analysis_imp_currency #(currency_transaction, vending_sb) currency_export;
  uvm_analysis_imp_dispense #(dispense_transaction, vending_sb) dispense_export;
  uvm_analysis_imp_cfg      #(cfg_transaction, vending_sb)      cfg_export;

  virtual vmc_if ctrl_vif;

  int selected_item;
  int no_of_items;
  int credit;
  int item_price = 10;

  function new(string name = "vending_sb", uvm_component parent = null);
    super.new(name, parent);
    item_export     = new("item_export", this);
    currency_export = new("currency_export", this);
    dispense_export = new("dispense_export", this);
    cfg_export      = new("cfg_export", this);

    selected_item = -1;
    no_of_items   = 0;
    credit        = 0;
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual vmc_if)::get(this, "", "ctrl_vif", ctrl_vif))
      `uvm_fatal("SCOREBOARD", "ctrl_vif not found in config DB");
  endfunction

  // ============================================================
  //  THESE ARE THE CORRECT CALLBACK NAMES (FROM THE MACROS)
  // ============================================================

  function void write_item(item_select_transaction tr);
    selected_item = tr.item_select;
    no_of_items   = tr.no_of_items;
    `uvm_info("SCOREBOARD",
              $sformatf("ITEM SELECTED -> item=%0d, count=%0d",
                        selected_item, no_of_items),
              UVM_LOW);
  endfunction

  function void write_currency(currency_transaction ct);
    credit += ct.currency_value;
    `uvm_info("SCOREBOARD",
              $sformatf("CURRENCY INSERTED -> %0d (Total Credit=%0d)",
                        ct.currency_value, credit),
              UVM_LOW);
  endfunction

  function void write_dispense(dispense_transaction dt);
    int expected_total_cost;
    int expected_change;

    if (ctrl_vif != null && !ctrl_vif.rstn) begin
      `uvm_error("SCOREBOARD", "RESET ACTIVE -> dispense received during reset");
      return;
    end

    if (selected_item == -1) begin
      if (dt.item_dispense != 0)
        `uvm_error("SCOREBOARD", "FAIL: DUT dispensed item without selection!");
      return;
    end

    expected_total_cost = item_price * no_of_items;
    expected_change     = credit - expected_total_cost;

    if (credit < expected_total_cost) begin
      if (dt.item_dispense != 0)
        `uvm_error("SCOREBOARD", "FAIL: Item dispensed with insufficient credit!");
    end
    else begin
      if (dt.item_dispense != selected_item) begin
        `uvm_error("SCOREBOARD",
                   $sformatf("FAIL: Wrong item. Expected %0d, got %0d",
                             selected_item, dt.item_dispense));
      end
      else if (dt.no_of_items_dispensed != no_of_items) begin
        `uvm_error("SCOREBOARD",
                   $sformatf("FAIL: Wrong count. Expected %0d, got %0d",
                             no_of_items, dt.no_of_items_dispensed));
      end
      else if (dt.currency_change != expected_change) begin
        `uvm_error("SCOREBOARD",
                   $sformatf("FAIL: Wrong change. Expected %0d, got %0d",
                             expected_change, dt.currency_change));
      end
      else begin
        `uvm_info("SCOREBOARD",
                  "PASS: Correct item, count, and change dispensed!",
                  UVM_LOW);
      end
    end

    selected_item = -1;
    credit        = 0;
    no_of_items   = 0;
  endfunction

  function void write_cfg(cfg_transaction cfg);
    `uvm_info("SCOREBOARD",
              $sformatf("CFG WRITE: addr=0x%0h data=0x%0h",
                        cfg.paddr, cfg.pwdata),
              UVM_LOW);
  endfunction

endclass


// `include "uvm_macros.svh"
// import uvm_pkg::*; 
// `uvm_analysis_imp_decl(_item)
// `uvm_analysis_imp_decl(_currency)
// `uvm_analysis_imp_decl(_dispense)
// `uvm_analysis_imp_decl(_cfg)

// class vending_sb extends uvm_scoreboard;
//   `uvm_component_utils(vending_sb)

//   uvm_analysis_imp#(item_select_seq_item, vending_sb)     item_export;
//   uvm_analysis_imp#(currency_transaction, vending_sb)     currency_export;
//   uvm_analysis_imp#(dispense_transaction, vending_sb)     dispense_export;
//   uvm_analysis_imp#(cfg_transaction, vending_sb)          cfg_export;

//   virtual vmc_if ctrl_vif;

//   int selected_item;
//   int no_of_items;
//   int credit;
//   int item_price = 10;

//   function new(string name = "vending_sb", uvm_component parent = null);
//     super.new(name, parent);
//     item_export     = new("item_export", this);
//     currency_export = new("currency_export", this);
//     dispense_export = new("dispense_export", this);
//     cfg_export      = new("cfg_export", this);

//     selected_item = -1;
//     no_of_items   = 0;
//     credit        = 0;
//   endfunction

//   function void build_phase(uvm_phase phase);
//     super.build_phase(phase);
//     if (!uvm_config_db#(virtual vmc_if)::get(this, "", "ctrl_vif", ctrl_vif))
//       `uvm_fatal("SCOREBOARD", "ctrl_vif not found in config DB");
//   endfunction

//   function void write_item(item_select_seq_item tr);
//     selected_item = tr.item_select;
//     no_of_items   = tr.no_of_items;
//     `uvm_info("SCOREBOARD",
//               $sformatf("ITEM SELECTED -> item=%0d, count=%0d",
//                         selected_item, no_of_items),
//               UVM_LOW);
//   endfunction

//   function void write_currency(currency_transaction ct);
//     credit += ct.currency_value;
//     `uvm_info("SCOREBOARD",
//               $sformatf("CURRENCY INSERTED -> %0d (Total Credit=%0d)",
//                         ct.currency_value, credit),
//               UVM_LOW);
//   endfunction

//   function void write_dispense(dispense_transaction dt);
//     int expected_total_cost;
//     int expected_change;

//     if (ctrl_vif != null && !ctrl_vif.rstn) begin
//       `uvm_error("SCOREBOARD", "RESET ACTIVE -> dispense received during reset");
//       return;
//     end

//     if (selected_item == -1) begin
//       if (dt.item_dispense != 0) begin
//         `uvm_error("SCOREBOARD", "FAIL: DUT dispensed item without selection!");
//       end
//       return;
//     end

//     expected_total_cost = item_price * no_of_items;
//     expected_change     = credit - expected_total_cost;

//     if (credit < expected_total_cost) begin
//       if (dt.item_dispense != 0) begin
//         `uvm_error("SCOREBOARD", "FAIL: Item dispensed with insufficient credit!");
//       end
//     end
//     else begin
//       if (dt.item_dispense != selected_item) begin
//         `uvm_error("SCOREBOARD",
//                    $sformatf("FAIL: Wrong item. Expected %0d, got %0d",
//                              selected_item, dt.item_dispense));
//       end
//       else if (dt.no_of_items_dispensed != no_of_items) begin
//         `uvm_error("SCOREBOARD",
//                    $sformatf("FAIL: Wrong count. Expected %0d, got %0d",
//                              no_of_items, dt.no_of_items_dispensed));
//       end
//       else if (dt.currency_change != expected_change) begin
//         `uvm_error("SCOREBOARD",
//                    $sformatf("FAIL: Wrong change. Expected %0d, got %0d",
//                              expected_change, dt.currency_change));
//       end
//       else begin
//         `uvm_info("SCOREBOARD",
//                   "PASS: Correct item, count, and change dispensed!",
//                   UVM_LOW);
//       end
//     end

//     selected_item = -1;
//     credit        = 0;
//     no_of_items   = 0;
//   endfunction

//   function void write_cfg(cfg_transaction cfg);
//     `uvm_info("SCOREBOARD",
//               $sformatf("CFG WRITE: addr=0x%0h data=0x%0h",
//                         cfg.paddr, cfg.pwdata),
//               UVM_LOW);
//   endfunction

// endclass
